### PR TITLE
feat: identity page

### LINKED ISSUE #683: Identity page
As user I'd like to see full identity metadata.

- [x] Add identity page and show metadata
- [x] Support identity renaming
- [x] Support identity removal

### PR DESCRIPTION
**Pull request by 0xmad**
## Explanation

This PR adds identity page to show user full identity metadata.

Details are below:
- [x] Add identity page
- [x] Fix firefox manifest v2
- [x] Minor refactoring for identity list item
- [x] Add delete and update identity actions
- [x] Add e2e test for identity page

## More Information

Closes #683 

## Screenshots/Screencaps

Extended mode:
image
image

Popup mode:
image
image

## Manual Testing Steps

1. Go to home
2. Open identity view
3. See identity metadata

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] Pre-commit and pre-push hook checks are passed
- [x] E2E tests are passed locally
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

**Comment by 0xisk** [comment]
Thanks @0xmad, I did a manual testing now and here are the UI screens for the identity options and the metadata page. Which they look different from what's in the PR description. 
Is that expected in this PR? 
- I dont see the `Delete` option in the identity options button on the left. 
- The Identity metadata has scrolls appear. Also the delete button doesn't work yet. 
Screenshot_20230811_214542
Screenshot_20230811_214509

**Comment by 0xmad** [comment]
@0xisk yes, this is expected. You can't delete connected identity.

**Review by 0xisk — APPROVED** [review]
Thank @0xmad the changes look good to me. Is the following PR after mergning that expcted to have the delete option in the metadata page working?

**Comment by 0xmad** [comment]
@0xisk it works for non-connected identity. The same behaviour has been already implemented for home page.

**Pull request merged**
