### PR TITLE
chore: eslint packages

### PR DESCRIPTION
**Pull request by 0xmad**
## Explanation

This PR adds eslint packages to reuse them among all the packages.

Details are below:
- [x] Create base eslint config
- [x] Create react eslint config
- [x] Add tsconfig.json to root

## More Information

Related to #92
Blocked by #528
Blocked by #529  

## Screenshots/Screencaps

N/A

## Manual Testing Steps

N/A

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

**Review by 0xisk — COMMENTED** [review]
I think `eslint-config-react` will be removed soon when I create a new repo for the ui part, `@cryptkeeper/ui`. Therefore at that time, we could rename `@cryptkeeper/eslint-config-base` to just `@cryptkeeper/eslint`.

**Comment by 0xmad** [comment]
`eslint-config-react` can be used across all ui packages (for example, ui kits and applications).

**Review by 0xisk — APPROVED** [review]
Thanks @0xmad! Just one comment, let's rename them to `@cryptkeeper/eslint-base` and `@cryptkeeper/eslint-react`

**Comment by 0xmad** [comment]
@0xisk this is a convention for eslint config packages so I'd keep them.
Here the examples:
```
eslint-config-airbnb
eslint-plugin-json
eslint-import-resolver-typescript
```

**Pull request merged**
