### PR TITLE
feat: update readme, icons

### PR DESCRIPTION
**Pull request by 0xisk**
## Explanation

Enhancing the README docs and the build icons. 

## More Information

N/A

## Screenshots/Screencaps

Screenshot_20230620_224130

## Manual Testing Steps

N/A

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

**Comment by 0xmad** [comment]
@0xisk this is current
image

**Comment by 0xisk** [comment]
> @0xisk this is current README file in github preview mode. I think it should have different alignment.
> 
> image

I think its better now, isn't it?

**Comment by 0xmad** [comment]
Logo's on the same position on the right side. I think it should be centered above the text and firefox link should be under the text aligned to the left side. Text should have left alignment, too.

**Review by 0xmad — APPROVED** [review]
Thanks @0xisk!

**Pull request merged**
