### PR TITLE
chore: optimize build

### LINKED ISSUE #107: Remove clean scripts
Optimize build process and keep it as simple as possible

### PR DESCRIPTION
**Pull request by 0xmad**
## Explanation

Get rid of clean scripts and replace source maps to get rid of eval code + improve build speed a little bit.

Details are bellow:
- [x] Remove clean scripts
- [x] Update source maps

## More Information

Fixes #107 

## Screenshots/Screencaps

N/A

## Manual Testing Steps

Just try to run `npm run dev` and `npm run build` to check if extension loads properly.

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

**Review by iskdrews — CHANGES_REQUESTED** [review]
Well I still cant approve this change since the eval code is still there not in the `dist/js/backgroundPage.js` script but in the `dist/js/injected.js` script in both builds the prod and the dev. That's because of moving the proof generation part from the background to the contentscript.

**Comment by 0xmad** [comment]
@iskdrews what's the exact error there? I can't see any eval errors and the demo works as expected.

**Comment by iskdrews** [comment]
> @iskdrews what's the exact error there? I can't see any eval errors and the demo works as expected.

There isn't any error, because the eval code is just moved the `dist/js/injected.js` still not sure if that would be accepted this way to be approved from chrome reviewers or not.

**Comment by AtHeartEngineer** [comment]
Ya I'm not seeing any errors on the cryptkeeper side, except for a `ObjectMultiplex - orphaned data for stream "publicConfig"` warning.

**Review by AtHeartEngineer — APPROVED** [review]
This is building and working good for me. I am not understanding the injection being an issue @iskdrews, could you explain that to me when you can?

**Comment by iskdrews** [comment]
> This is building and working good for me. I am not understanding the injection being an issue @iskdrews, could you explain that to me when you can?

I think all is good now, as @0xmad said it is just an hardcoded value and it doesn't take any inputs so no security risk.

**Review by iskdrews — APPROVED** [review]

**Comment by iskdrews** [comment]
> Ya I'm not seeing any errors on the cryptkeeper side, except for a `ObjectMultiplex - orphaned data for stream "publicConfig"` warning.

There is an issue for tracking resolving this warning already, but not resolved yet. 
https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/111

**Pull request merged**
